In [1]:
import numpy as np

In [4]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

**#1 How many negative numbers are there?**

In [23]:
negative_numbers = a[a < 0]
print(negative_numbers)
negative_numbers.size
a

[-2 -1 -6 -7]


array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

**#2 How many positive numbers are there?**

In [25]:
positive_numbers = a[a > 0]
positive_numbers.size

5

**#3 How many even positive numbers are there?**

In [97]:
#positive_even_numbers = np.where((a > 0) & (a % 2 == 0)) #works not like i need
print(a)
positive_even_numbers = (a[a % 2 == 0])[(a[a % 2 == 0]) > 0]
print(positive_even_numbers)

[ 4 10 12 23 -2 -1  0  0  0 -6  3 -7]
[ 4 10 12]


In [42]:
# positive_even_numbers2 = a[(a > 0) and (a % 2 == 0)]

**#4 If you were to add 3 to each data point, how many positive numbers would there be?**

In [5]:
plus_3_positive = a + 3
plus_3_positive = (a + 3)[a > 0]
plus_3_positive.size


5

**#5 If you squared each number, what would the new mean and standard deviation be?**

In [8]:
squared_array = a ** 2
squared_mean = np.mean(squared_array)
squared_std = np.std(squared_array)
print(f'Mean is {squared_mean}, STD is {round(squared_std, 2)}')

Mean is 74.0, STD is 144.02


**#6 A common statistical operation on a dataset is centering. 
This means to adjust the data such that the mean of the data is 0. 
This is done by subtracting the mean from each data point. Center the data set.**

In [13]:
#mean = np.mean(a)
centered_array = a - int(np.mean(a))
np.mean(centered_array)

0.0

**#7 Calculate the z-score for each data point.**

In [23]:
zscores = (a - int(np.mean(a))) / np.std(a)
zscores = np.array([round(z, 2) for z in zscores])
zscores

array([ 0.12,  0.87,  1.12,  2.48, -0.62, -0.5 , -0.37, -0.37, -0.37,
       -1.12,  0.  , -1.24])

### More exersices

In [24]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

**Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list**

In [47]:
sum_of_a = sum(a)
print(sum_of_a) #55
sum_of_a = np.array(a).sum()
print(sum_of_a)

55
55


**Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list**

In [48]:
min_of_a = min(a)
print(min_of_a) #1
min_of_a = np.array(a).min()
print(min_of_a)

1
1


**# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list**

In [56]:
max_of_a = max(a)
print(max_of_a) #10
#with numpy
max_of_a = np.array(a).max()
print(max_of_a)

10
10


**# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list**

In [34]:
mean_of_a = sum(a) / len(a)
#or
mean_of_a = np.mean(a)
mean_of_a

5.5

**# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together**

In [35]:
product_of_a = np.prod(a)
product_of_a #3628800

3628800

**# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]**

In [37]:
squares_of_a = [n ** 2 for n in a]
print(squares_of_a)
#or
squares_of_a = np.array(a) ** 2
print(squares_of_a)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
[  1   4   9  16  25  36  49  64  81 100]


**# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers**

In [42]:
odds_in_a = [n for n in a if n % 2 == 1]
print(odds_in_a)
# or with numpy
odds_in_a = np.array(a)[np.array(a) % 2 == 1]
print(odds_in_a)

[1, 3, 5, 7, 9]
[1 3 5 7 9]


**# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.**

In [43]:
evens_in_a = [n for n in a if n % 2 == 0]
print(evens_in_a)
#or with numpy
evens_in_a = np.array(a)[np.array(a) % 2 == 0]
print(evens_in_a)

[2, 4, 6, 8, 10]
[ 2  4  6  8 10]


### 2D arrays
**What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...**
*Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.*

In [44]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

*Transform b into a numpy array*

In [52]:
b_arr = np.array(b)
print(b_arr)

[[3 4 5]
 [6 7 8]]


**# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**

```python
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)
```

In [54]:
sum_of_b = b_arr.sum()
print(sum_of_b)

33


**# Exercise 2 - refactor the following to use numpy.**
```python
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])
```

In [55]:
min_of_b = b_arr.min()
print(min_of_b)

3


**# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.**
```python
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])```


In [57]:
max_of_b = b_arr.max()
print(max_of_b)

8


**# Exercise 4 - refactor the following using numpy to find the mean of b**
```python
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))
```

In [58]:
mean_of_b = b_arr.mean()
print(mean_of_b)

5.5


**# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.**
```python
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
```

In [59]:
prod_of_b = np.prod(b_arr)
print(prod_of_b)

20160


**# Exercise 6 - refactor the following to use numpy to find the list of squares **
```python
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
```

In [60]:
squares_of_b = b_arr ** 2
print(squares_of_b)

[[ 9 16 25]
 [36 49 64]]


**# Exercise 7 - refactor using numpy to determine the odds_in_b**
```python
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
```

In [65]:
odds_in_b = b_arr.flatten()[b_arr.flatten() % 2 == 1]
#or
b_arr_list = b_arr.flatten() #I use it in the next exercise
odds_in_b = b_arr_list[b_arr_list % 2 != 0]

print(odds_in_b)

[3 5 7]


**# Exercise 8 - refactor the following to use numpy to filter only the even numbers**
```python
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
```

In [66]:
evens_in_b = b_arr_list[b_arr_list % 2 == 0] #b_arr_list from the previous exercise
print(evens_in_b)

[4 6 8]


**# Exercise 10 - transpose the array b.**

In [73]:
b_transposed = b_arr.transpose((1, 0))
print(b_transposed)

[[3 6]
 [4 7]
 [5 8]]


**# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)**

In [83]:
b_arr_list = b_arr.reshape(1, 6)
print(b_arr_list)

[[3 4 5 6 7 8]]


**# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)**

In [86]:
arr_vertical = b_arr.reshape(6, 1)
print(arr_vertical)

[[3]
 [4]
 [5]
 [6]
 [7]
 [8]]


##  3D arrays

In [87]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [88]:
#transform c to a numpy array
c = np.array(c)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**# Exercise 1 - Find the min, max, sum, and product of c.**

In [90]:
min_of_c = c.min()
max_of_c = c.max()
prod_of_c = c.prod()
print(f'Min is {min_of_c}, \nMax is {max_of_c}, \nProduct is {prod_of_c}')

Min is 1, 
Max is 9, 
Product is 362880


**# Exercise 2 - Determine the standard deviation of c.**

In [91]:
std_of_c = c.std()
print(std_of_c)

2.581988897471611


**# Exercise 3 - Determine the variance of c.**

In [93]:
var_of_c = c.var()
var_of_c

6.666666666666667

**# Exercise 4 - Print out the shape of the array c**

In [96]:
print(c.shape)

(3, 3)


**# Exercise 5 - Transpose c and print out transposed result.**

In [104]:
print(c.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


**# Exercise 6 - Get the dot product of the array c with c.**

In [103]:
dot_prod = np.dot(c, c)
print(dot_prod)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


**# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261**

In [105]:
sum_with_transpose = (c * c.transpose()).sum()
sum_with_transpose

261

**# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400**

In [106]:
prod_with_transpose = (c * c.transpose()).prod()
prod_with_transpose

131681894400

## Setup 4

In [3]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

In [4]:
d = np.array(d)

**# Exercise 1 - Find the sine of all the numbers in d**

In [47]:
sin_d = np.sin(d)
sin_d

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

**# Exercise 2 - Find the cosine of all the numbers in d**

In [48]:
cos_d = np.cos(d)
cos_d

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

**# Exercise 3 - Find the tangent of all the numbers in d**

In [49]:
tan_d = np.tan(d)
tan_d

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

**# Exercise 4 - Find all the negative numbers in d**

In [50]:
np.shape(d)

(3, 6)

In [63]:
d[2] < 0

array([False, False,  True, False,  True, False])

In [52]:
#solved with python list, need to find a way to solve with numpy only
neg_d = []
for x in d:
    for y in x:
        if y < 0:
            neg_d.append(y)
neg_d

[-90, -30, -45, -45]

In [8]:
np.shape(d)
neg_d1 = d[d < 0]
neg_d1

array([-90, -30, -45, -45])

**# Exercise 5 - Find all the positive numbers in d**

In [9]:
np.shape(d)
neg_d1 = d[d > 0]
neg_d1

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

**# Exercise 6 - Return an array of only the unique numbers in d.**

In [11]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

**# Exercise 7 - Determine how many unique numbers there are in d.**

In [15]:
np.unique(d).size

11

**# Exercise 8 - Print out the shape of d.**

In [16]:
np.shape(d)

(3, 6)

**# Exercise 9 - Transpose and then print out the shape of d.**

In [20]:
np.shape(np.transpose(d))

(6, 3)

**# Exercise 10 - Reshape d into an array of 9 x 2**

In [23]:
np.reshape(d, (9, 2))

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])